### ISSUE TITLE
A Microsoft Office key feature missing from Microsoft Excel which almost certainly hampers the capabilities developable within the AFE add-in

### ISSUE THREAD

**Issue by no-identd** [microsoft/advanced-formula-environment#12]
https://word.tips.net/T000964_Changing_the_Default_File_Name.html, Word 95 can do it, Excel 365 still can't.

See also:
BOOK.XLTX, SHEET.XLTX, PERSONAL.XLSB, Ctrl+N, [SemVerDoc.org](https://semverdoc.org/), MS Word Cover Pages, #6, #9

I mean, I WANT to put an end to e-mail as horrendous version control for Microsoft Excel documents but you guys make it really hard.

BUT ALSO, THANK YOU SO MUCH already for all the hard work you've put in to implement all this. I can smell the stale air leaving.
😘😘😘

#RecalcOrDie

P.S.:
After you've finished all up on Excel & while on the topic of feature parity making life easier for everyone, please could someone add a good ending to this Computer Science list continuation & transclusion nightmare from hell next:
[http://www.addbalance.com/word/MasterDocHudson.htm](http://www.addbalance.com/word/MasterDocHudson.htm) (the meta-workaround for which consists of [http://www.gmayor.com/Boiler.htm](http://www.gmayor.com/Boiler.htm))

Also, the Nightmare™ of the Microsoft Word Wizard .WIZ file format. And bring back InfoTip localisation packs for crying out loud whoever cut that feature needs to be forced to work multilingual L1 support for a decade. Think of all the guys over in #1, #2, #3, they have to ~~Google~~ _Bing™_  formulas in English all day but use localised Excel to communicate with end-users. How do you think that works? (sorry, yes, this is off-topic, but I feel bitter. See also: Double-clicking comma-separated .csv files with localized MS Excel installed. Like, seriously, it's 2022? ☹️ And don't get me started on using named ranges inside conditional formatting & data validation.)

**Comment by jack-williams** [comment]
Thank you for the feedback @no-identd. I would like to keep this issue tracker specifically for issues/bugs/suggestions for AFE, rather than Excel generally. I'm going to close this, but feel free to create a more specific issue related to AFE.
