### ISSUE TITLE
AFE for (unnamed) cell formulas

### ISSUE THREAD

**Issue by derfasthirnlosenick** [microsoft/advanced-formula-environment#15]
I'd be great to be able to use the AFE features (e.g. indentation, highlighting, intellisense etc.) while editing an unnamed formula in the active cell.

Rationale: There's a whole lot of Excel-sheets out there that use rather complex / long formulas that are only used once and are therefore not immediate candidates for naming / lambda. However, editing / maintaining such formulas could benefit greatly from the AFE features mentioned above.

The most straightforward way would be to place an additional card "Active Cell Formula" at the top of the list in the "Manager" Tab. It would make sense to create some visual distinction from the named formulas, e.g. by using a visual separator or having the formula be a slightly different colour.

**Comment by jack-williams** [comment]
Agree with your rationale. Even being able to view the formulas using the formatted cards would helpful, in my view.

This is something I've looked into adding, but not committed too yet. Will mark as a feature request.

**Comment by jack-williams** [comment]
The new AFE now supports editing the current cell.
