### ISSUE TITLE
AFE disappears from ribbon

### ISSUE THREAD

**Issue by SergeiStPete** [microsoft/advanced-formula-environment#18]
Perhaps it was discussed, didn't find. AFE disappears from the ribbon from time to time. Can't say if same happens with other add-ins, have only AFE of such kind. Perhaps it's since I'm shifting from VPN to not VPN connection periodically, don't know. At least I can't reproduce that intentionally.
Not a big job to add AFE again from My Add-Ins, but better to fix.

**Comment by jack-williams** [comment]
I've only seen something like this when I've been changing my trusted add-in catalogue or deleting the office cache. I've not seen or had any reports of "normal" usage causing the add-in to disappear.

Does this happen exclusively with AFE, or do other task-pane add-ins also disappear?

I will close this for now. If others have the same problem I will re-open.
