### ISSUE TITLE
Does not work when formula argument separator is not a comma

### ISSUE THREAD

**Issue by vzczc** [microsoft/advanced-formula-environment#2]
I opened an existing workbook with a number of valid lambda functions, but when opened in the advanced formula environment, the formula is not there, it shows an error where the first semicolon (argument separator in my locale) appears.

**Comment by jack-williams** [comment]
Unfortunately we do not have multiple locale support, and we assume that the argument separator is `,`. I've created #3 to track this issue centrally and I will close this. Feel free to continue any discussion on that thread.
