### ISSUE TITLE
Named tables not seen by AFE

### ISSUE THREAD

**Issue by ammosov** [microsoft/advanced-formula-environment#22]
Suppose I have a named table defined. Name Manager sees it. 

![image](https://user-images.githubusercontent.com/4894284/198985549-a194b7a2-eda2-4691-9831-052f55bd0cd7.png)

Expected behavior: table name can be referenced as typed. 

![image](https://user-images.githubusercontent.com/4894284/198986075-b6290991-8abb-45dc-b08b-32d02ef8d370.png)

Actual behavior: it does not. Named functions are seen alright, though.

**Comment by jack-williams** [comment]
We'll add this.

**Comment by ammosov** [comment]
> We'll add this.

Thanks chief! And tnx for an amazing product. Posted a review in my Telegram channel today.
