### ISSUE TITLE
AFE 1.1 formatting

### ISSUE THREAD

**Issue by SergeiStPete** [microsoft/advanced-formula-environment#27]
I re-read documentation, my understanding it assumes that formula in currently selected cell is shown in formatted way in grid view. On practice it happens only if close and open AFE staying on the cell with formula.
Also, found no way to keep such formatting and format formulae in Modules and Names->Formulas blocks.

Did I miss something?

**Comment by jack-williams** [comment]
I had some trouble understand the problem. Would you be able to provide some steps to reproduce the problem?

On grid view, when moving the selection to a new cell, AFE will format the formula to fit within the taskpane. When commiting the formula, AFE will write it out on a single line. While editing the formula in AFE, we will not automatically update the format, but you can invoke this using the context menu or Ctrl + Shift + f.

Is that not working for you?

**Comment by SergeiStPete** [comment]
I was wrong. To re-format I shall go on another cell, resize right pane and go back on the cell. Not just resizing pane staying on the cell.
