### ISSUE TITLE
Purpose of hidden sheet

### ISSUE THREAD

**Issue by vzczc** [microsoft/advanced-formula-environment#30]
When you create a new file and start adding modules and formulas to it, a very hidden sheet is created. This contains some functions and data that seems to be without purpose.

After adding a few modules with some definitions, I see that these seem to be stored in an embedded XML document, but nothing changes in the hidden sheet. Deleting the very hidden sheet does not seem to have an impact on anything.

What is the purpose of the very hidden sheet? Is it related to an older version of AFE that is no longer in use, or does it have some purpose

**Comment by jack-williams** [comment]
The very hidden sheet is used to test the locale of the workbook to determine properties such as the argument separator. Currently, these are not provided by the JavaScript API.

**Comment by vzczc** [comment]
Could you not simply use a formula like this to determine the decimal separator 
=MID(VALUE(NUMBERVALUE("1%")),2,1)
if it returns ","  argument separator is ";"  and decimal separator is "," 
else argument separator is ";", and decimal separator="."

**Comment by jack-williams** [comment]
Perhaps, but as the list separator is a specific setting I’d prefer to test it directly rather than infer it. There are addition localisation features we must also test for.

**Comment by NagyGa1** [comment]
Would be better if this sheet is not in the saved workbook.

If kept, please keep the name `e00eb4de3c8a421cba9b8f4cb8546ec` so everyone downstream can filter it out by the name.

**Comment by jack-williams** [comment]
We’ll make a change to remove it once done

**Comment by NagyGa1** [comment]
Thank you very much.
