### ISSUE TITLE
Enable change the order of the function argument in Name tab

### ISSUE THREAD

**Issue by dlealv** [microsoft/advanced-formula-environment#42]
Currently, there is no way to change the order of the function arguments, not a big deal for a few arguments, but if you have several of them, and just decide to change the order, you need to remove all of them and recreate them again with the new order.
<img width="707" alt="image" src="https://user-images.githubusercontent.com/9689133/225510120-182ceae5-a757-4255-9f98-7b1c1d870fac.png">

In the above example if I want y to be the first argument and x the second I need to remove them an recreate them again.

I tested in Excel for Web.

Thanks,

David

**Comment by jack-williams** [comment]
@dlealv, we have an unpublished user-interface update that improves the experience of defining functions. I'll close this once it is live.

cc @NWilson

**Comment by jack-williams** [comment]
We have merged a new change that updates the argument UI. The arguments are now inline pills so a user can delete and add pills at any position.

![image](https://user-images.githubusercontent.com/4489219/227069615-856dc832-9285-4bef-bd93-181b218e3ad1.png)

**Comment by dlealv** [comment]
Thanks I tested it and it works!!!
