### ISSUE TITLE
Sync to and from Name Manager

### ISSUE THREAD

**Issue by cowenB2Q** [microsoft/advanced-formula-environment#5]
Love it! Is there intent to add functionality that adds existing and traditionally created named ranges to the Editor/fully sync with name manager? It looks like the data only flows in one direction right now.

Plus, an option to add any AFE comments to the traditional "Comments" block in name manager to be seen by people without the add-in would be very useful.

**Comment by jack-williams** [comment]
Thanks @cowenB2Q!

When the add-in is running in the mode without hidden sheet metadata (controlled under settings), the add-in should read all workbook names from the manager and display them.

When the add-in is running in the mode _with_ hidden sheet metadata, we only display the names created by the add-in.

This is not well documented, and I'm tracking that in #6.

> Plus, an option to add any AFE comments to the traditional "Comments" block in name manager to be seen by people without the add-in would be very useful.

Yes, agreed. I think a reasonable solution would be to have the leading comment before a definition (as present in Editor view) be saved into the Name Manager comment field.

**Comment by AlexC84** [comment]
this also looks to cause an issue with cell references in the AFE no being updated when someone drags the target cell in the worksheet to a new location. The cell reference in the Name Manager is updated but it is never synced back to the AFE which continues to reference an out of date address

**Comment by mitchcapper** [comment]
> Yes, agreed. I think a reasonable solution would be to have the leading comment before a definition (as present in Editor view) be saved into the Name Manager comment field.

I went ahead and did this (syncing the first line if it started with // to the comment field for Names and back). However it is unclear if this repo wants code PR for a chunk like that.   Given there is no source code here I would assume not, but it does specify a license and contributor guidelines as well.  

AFE is fantastic but for those of us who may not use it all the time (or have consumers w/o) the ability for the names panel having the comments is useful.

**Comment by jack-williams** [comment]
The new AFE now reflects the full content of the name manager as we have separated out the concepts of manager names (defined using the name manager wizard) and modules (defined using code). Both support modifying the description field of the underlying name.
