### ISSUE TITLE
Feature request: edit Python

### ISSUE THREAD

**Issue by ammosov** [microsoft/advanced-formula-environment#54]
Subj. + https://techcommunity.microsoft.com/t5/excel-blog/announcing-python-in-excel-combining-the-power-of-python-and-the/ba-p/3893439

**Comment by SergeiStPete** [comment]
That will be great. Having no other environment I use Notepad++ for editing Python script, AFE will be much more suitable for Excel-only people.

**Comment by jack-williams** [comment]
Closing this

https://techcommunity.microsoft.com/t5/excel-blog/introducing-the-python-editor-from-excel-labs/ba-p/3928986
