### ISSUE TITLE
No clarification for using of hidden sheet

### ISSUE THREAD

**Issue by SergeiStPete** [microsoft/advanced-formula-environment#6]
It was alert that comments / formatting are supported with hidden sheet only, can't see it now. If it's still so perhaps it's better permanently to have such text near setting.

**Comment by jack-williams** [comment]
Thanks @SergeiStPete. I'm going to add some more detailed documentation about how the hidden sheets work to this repository. Might also be helpful to include the alert text under the settings page. Once I've added the documentation to this repository, I'll close this issue.

It is also on my roadmap to try and support formula comments without the use of the hidden sheet.
