### ISSUE TITLE
Providing function descriptions in Module

### ISSUE THREAD

**Issue by NickRedwood** [microsoft/advanced-formula-environment#62]
Hi,

It's nice how it's possible to add a function description in the Names section, so that it appears as a tool tip when writing the formula in the Excel grid. Is there a way to define descriptions for functions in Modules too? I can't find it documented anywhere.

Thanks.

**Comment by jack-williams** [comment]
You can use leading `/** */` comments.

```
/**
 * My function that adds one
 */
add_one = LAMBDA(x, x + 1);
```

**Comment by NickRedwood** [comment]
Thank you!
That's really great.
