### ISSUE TITLE
Gist import failing

### ISSUE THREAD

**Issue by KDean-Dolphin** [microsoft/advanced-formula-environment#66]
I'm getting an error when I try to import any Gist module. This is what I see in AFE:

Importing formulas failed: undefined is not an object (near '...usting:(0,x.zO)()})).data}catch(t){throw...')

If you want a simple module to test with, here it is:

https://gist.github.com/KDean-Dolphin/d94ab4ffb22a203e0068207b0ad25c7d

**Comment by jack-williams** [comment]
Thanks for finding this, will look into it

**Comment by jack-williams** [comment]
I found the issue. Will aim to have a fix deployed tomorrow

**Comment by jack-williams** [comment]
Fix should be live now. Sorry for any inconvenience!
