### ISSUE TITLE
Hidden Sheet - needs to make clearer that comments & formatting will be lost

### ISSUE THREAD

**Issue by StarTech-Enterprises** [microsoft/advanced-formula-environment#9]
Hi, 

I think if you turn the Hidden Sheet option off, there should be a warning that says all the comments and formula formatting will be lost. In my case even some of the formulas broke when I turned this option off (and closed and opened Excel), but then I had to upgrade to the latest version of Excel. Then only the comments and formula formatting were lost. 

If users rely on the Hidden Sheet, and then it's turned off by accident, it can easily *break* the whole workbook. Whilst I know you do not consider Hidden Sheet as a long term solution, there should be a clearer warning of what will happen when this option is turned off, so the user properly understands its affect.

**Comment by StarTech-Enterprises** [comment]
Hi Jack, I am using the latest Excel Build 16.59 (22020901) on Mac

I'm thinking from the perspective of sharing the workbook, and other users who (i) might not have the latest Excel build (ii) might have the hidden sheet setting turned off.... it would *break* the whole workbook... : (

Hope you Supersmart people and Supersmart engineers can solve it!

Sachin

**Comment by jack-williams** [comment]
Closing this because hidden sheets are now deprecated in the new version of AFE. The code files are always stored with the document and are manager separately from names defining using the name manager. As a result, there is no hidden-sheet option.
